---
- hosts: localhost
  become: true
  
  vars:
    - homeDir:  /home/fruiz
    - appDir :  prod
    - repo:  node_prueba
    - account: ruzfelipe
    - privateKey: /home/fruiz/.ssh/id_rsa
    - server_port: 8081
    - git_repo_url: https://github.com/ruizfelipe/node_prueba.git
    - repo_path: /home/ubuntu/prod
    - repo_branch: main

  tasks:
    - name: Create App Directory
      ansible.builtin.file: 
        path: "{{homeDir}}/{{appDir}}" 
        state: directory
        mode: '0755'
      
    - name: Clone a repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_path }}"
        version: "{{ repo_branch }}"
    
    - name: Copy folder to /var/www
      copy:
        src: "{{ repo_path }}"
        dest: /var/www
        remote_src: no
        
    - name: Copy files
      copy:
        owner: root
        group: root
        src: "{{ item.0 }}"
        dest: "{{ item.1 }}"
        mode: "0400"
      with_together:
        - ['prueba.conf']
        - ['/etc/nginx/sites-available/prueba.conf']
    
    - name: update apt list
      apt: 
        update_cache: yes

    - name: Install nginx
      apt: pkg=nginx state=latest
      notify: 
        - start nginx
        
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default  
        
    - name: Create a symbolic link
      file:
        src: /etc/nginx/sites-available/prueba.conf
        dest: /etc/nginx/sites-enabled/prueba.conf
        state: link  
        
    - name: Restart nginx service
      service:
        name: nginx
        state: restarted

  handlers:
    - name: start nginx
      service: name=nginx state=started
...
